version: 2
updates:
  # Enable version updates for npm
  - package-ecosystem: pub
    directory: "/"
    target-branch: "develop"
    schedule:
      interval: weekly

  - package-ecosystem: github-actions
    directory: "/"
    target-branch: "develop"
    schedule:
      interval: weekly